import rtconfig
from building import *

cwd = GetCurrentDir()
objs = []
group = []
list = os.listdir(cwd)

src = Glob(str(cwd)+'/*.c')
path = [cwd, str(Dir('#'))]
group = group + DefineGroup('Application', src, depend = [''], CPPPATH = path)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isdir(path):
        src = Glob(str(path)+'/*.c')
        group = group + DefineGroup('Usr/' + str(d), src, depend = [''], CPPPATH = [path])

Return('group')
